#!/usr/bin/env python3

import sys
import myimage
import time
lena = myimage.Image.load(sys.argv[1])
total_dt = 0
for method in myimage.dithering.DITHERING_METHODS:
    print(f"{method:15}", end="- ")
    t0 = time.time()
    lena.dithering(method).save(sys.argv[2] + "/" + method + ".png")
    dt = (time.time() - t0) * 1000
    total_dt += dt
    print(f"{dt:>6.1f} ms")
print(f"TOTAL: {total_dt:.1f} ms")
