#!/usr/bin/env python3

from imagetools import Image
from pathlib import Path
import sys

img = Image.load(sys.argv[1])
if len(sys.argv) > 2:
    palette = eval("{" + sys.argv[2] + "}")
else:
    palette = img.create_palette()
img = img.apply_the_palette(palette)
html = img.to_html()
html = f"<html><head><link rel=\"stylesheet\" href=\"styles.css\"></head><body>{html}</body></html>"
Path('index.html').write_text(html)
css = img.to_css()
css += '\ntable.pixelart { border-collapse: collapse; }'
css += '\ntable.pixelart tr td { width: 1em; height: 1em; }'
Path('styles.css').write_text(css)
